CREATE DATABASE IF NOT EXISTS tictactoe;
USE tictactoe;

CREATE TABLE IF NOT EXISTS leaderboard (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nickname VARCHAR(64) NOT NULL UNIQUE,
  wins INT DEFAULT 0,
  losses INT DEFAULT 0,
  draws INT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  player_x VARCHAR(64),
  player_o VARCHAR(64),
  winner VARCHAR(64),
  moves JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_nickname ON leaderboard(nickname);